name: Hexo Build and Deploy

on:
  push:
    branches: main  # 触发分支（根据你的默认分支名修改）

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    # 1. 检出代码
    - name: 1. 检出代码
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # 重要！确保主题子模块被拉取
        fetch-depth: 0  # 重要！确保拉取完整历史记录

    # 2. 设置 Node.js 环境
    - name: 2. 设置 Node.js 环境
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'  # 推荐 LTS 版本

    # 3. 缓存 node_modules 加速构建
    - name: 3. 缓存 node_modules 加速构建
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    # 4. 安装依赖
    - name: 4. 安装依赖
      run: |
        npm ci --prefer-offline
        npm install hexo-cli -g

    # 5. 生成静态文件
    - name: 5. 生成静态文件
      run: |
        hexo clean
        hexo generate

    # 6. 部署到 GitHub Pages
    - name: 6. 部署到 GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}  # 自动注入无需配置
        publish_dir: ./public  # Hexo 输出目录
        publish_branch: gh-pages  # 部署到的分支